import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ['latin'] });
const roboto_condensed = Roboto_Condensed({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "WebbyWolf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} ${roboto_condensed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
